[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dirm"
version = "0.1.0"
description = "Git-like CLI for managing directories"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
dirm = "dirman.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
